### ISSUE TITLE
Specify timezone in date formats

### ISSUE THREAD

**Issue by billowsofcode** [HaaLeo/vscode-timing#41]
**Is your feature request related to a problem? Please describe.**
I want to convert epoch time to human readable time in other time zones besides UTC and local.  For example I want to know what the epoch time is in MST even though I may computer local time is EST.  I often want to view an epoch time is multiple timezones with the hover feature.

**Describe the solution you'd like**
It would be good to support passing in a timezone, below are two suggested ways:

```json
 "timing.hoverTimestamp.targetFormat": [
        {
            "customFormat": "DD.MM.YYYY HH:mm:ss",
            "utcOffset": "-0700",
            "name": "My Format"
        },
        {
            "customFormat": "DD.MM.YYYY HH:mm:ss",
            "timezone": "America/Phoenix",
            "name": "My Format"
        }
    ]

```
In momentjs terms this would be:

```javascript
// set timezone using offset
moment(1369266934311).utcOffset('-0700').format('YYYY-MM-DD HH:mm')
// set timezone using named value 
moment(1369266934311).tz('America/Phoenix').format('YYYY-MM-DD HH:mm')
```

Named timezones list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by HaaLeo** [comment]
@billowsofcode thank you for your contribution. I just want to share my first thoughts on this:
* I could imagine a `timezone` option for the hover provider that takes arguments like `"America/Phoenix"` as well as `"-0700"`
* Then the `localize` parameter can be deprecated in favor for the `timezone` parameter
* In order to stay consistent with the command palette commands one should also add the corresponding command `... ⟶ ISO 8601` commands
* I am unsure whether I should deprecate the `... ⟶ ISO 8601 Local` and `... ⟶ ISO 8601 UTC` commands since I think those are the most common use cases.

**Comment by HaaLeo** [comment]
Since I do not want to overload the command palette I will only the commands `epochToIsoTimezone` as well as `epochToCustomTimezone`. However, the concept of the hover provider stays the same as suggested in the previous comment.
