### ISSUE TITLE
Support microseconds

### ISSUE THREAD

**Issue by depascalis** [HaaLeo/vscode-timing#43]
**Problem**
The extension seems to be unable to convert microseconds (1/1 000 000 second) and there's also no option for it in the settings.

**Solution**
Added support for μs would be helpful.

**Comment by HaaLeo** [comment]
@depascalis thank you for your contribution. I agree that microsecond support is overdue. 
However, it will be tricky to support it in an backwards compatible fashion, since it will most likely affect the nanoseconds conversion. 

One approach could be to turn it off by default. I'll try to figure out a smooth backwards compatible way

**Comment by depascalis** [comment]
@HaaLeo wow that's got to be a record, well done 👏
